### ISSUE TITLE
Expose the transport in LedgerContextSigner

### ISSUE THREAD

**Issue by Esya** [oasisprotocol/oasis-sdk#102]
In the constructor of LedgerContextSigner, we should probably expose the transport as public, or as private and proxy certain method to the transports.

As mentioned in https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-webusb of the two use cases : 

1- Briefly open/do an operation (get the address, sign a transaction/close, each time
2- Keep it open, but listen for webusb events (device unplugged), and the user might want to "close" his wallet in the GUI and reopen it later

We currently cannot do either of those usecases since the transport is not exposed, so we cannot call `close` on it and we cannot listen to events

I propose simply adding `transport` to the constructor and making it public for now, but happy to discuss a more advanced API 

https://github.com/oasisprotocol/oasis-sdk/blob/c6cb460c61f1ac75115dbc177896b220ccef3032/client-sdk/ts-web/signer-ledger/src/index.ts#L28-L58

**Comment by pro-wh** [comment]
I think what I'd like is to have `fromWebUSB` take either `transport` or `app` as an input. Thanks for posting the use cases. Can you work around this by replicating the internals of `fromWebUSB` for now?
