### ISSUE TITLE
ts-web: crashes in the latest npm published version @oasisprotocol/client 0.1.0-alpha9

### ISSUE THREAD

**Issue by aka-rider** [oasisprotocol/oasis-sdk#1160]
```js
global.XMLHttpRequest = require('xhr2');
const oasis = require('@oasisprotocol/client')


const nic = new oasis.client.NodeInternal('http://localhost:42280')

const i = async () => {
    const status = await nic.nodeControllerGetStatus()
    console.log(status)
}
i()
```

```
$ node test.js
.../node_modules/@oasisprotocol/client/dist/client.js:164
        const method = this.base + desc.getName();
                                        ^

TypeError: desc.getName is not a function
    at NodeInternal.callUnary (.../node_modules/@oasisprotocol/client/dist/client.js:164:41)
    at NodeInternal.nodeControllerGetStatus (.../node_modules/@oasisprotocol/client/dist/client.js:994:21)
    at i (.../test.js:8:30)
    at Object.<anonymous> (.../test.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47
```

This error doesn't exist in `main` branch but updated npm package has not been published

**Comment by aka-rider** [comment]
Hey, thank you for picking up the issue. 

While you are at it, can I ask you to update (deprecate?) the npm package [https://www.npmjs.com/package/@oasisprotocol/client](https://www.npmjs.com/package/@oasisprotocol/client).

At the very least, could you please add GitHub repo link to the npm package, otherwise it's all very confusing.

Mini-howto in the README will be very useful.

- Can you please explain that your SDK doesn't support node.js — only browser.
- Can you state that you don't support npm — only yarn.
- Links yo envoy config would be useful too

**Comment by pro-wh** [comment]
> desc.getName()

upgrade to grpc-web 1.4.1

> update (deprecate?) the npm package https://www.npmjs.com/package/@oasisprotocol/client

https://www.npmjs.com/package/@oasisprotocol/client/v/0.1.1-alpha.1 outdated version shown due to npm erroneously also tagging the earliest alpha as `latest` ):

> add GitHub repo link to the npm package

that's added recently, but we haven't made a release. @kostko could you review https://github.com/oasisprotocol/oasis-sdk/pull/1139 for us to ship this change

> Can you please explain that your SDK doesn't support node.js — only browser.

sounds good, we should

> Can you state that you don't support npm — only yarn.

that's not meant to be, could you file an issue if it's not working with npm?

> Links yo envoy config would be useful too

sounds good, we should

**Comment by pro-wh** [comment]
they're published on the alpha tag

![image](https://user-images.githubusercontent.com/38229038/195420784-f8cfd5a1-bf23-4720-bb8a-d4a80647a11f.png)

**Comment by aka-rider** [comment]
Ok. Clear. Thanks for the explanation.

**Comment by pro-wh** [comment]
correction, grpc-web 1.4.1 does not fix this. instead, downgrade to 1.3.x

**Comment by pro-wh** [comment]
https://www.npmjs.com/package/@oasisprotocol/client/v/0.1.1-alpha.2 includes a change to be compatible with grpc-web 1.4.0 and 1.4.1
