### ISSUE TITLE
ts-web: marginal gRPC services

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-sdk#13]
`RegisterService` calls that need some review

* [x] control grpc_debug -> this one I'll add in #10 
* [ ] IAS -> separate socket
* [x] runtime enclaverpc -> done
* [ ] sentry -> separate socket
* [x] worker storage -> internal socket #62

**Comment by kostko** [comment]
> IAS -> separate socket

This probably doesn't need to be exposed via the client SDK at this time.

> runtime enclaverpc -> I threw it into index, but it's actually served on a separate socket.

The `enclaverpc.Transport` service is actually exposed  (see [runtime client API](https://github.com/oasisprotocol/oasis-core/blob/master/go/runtime/client/api/api.go#L44)) via the internal socket so it should be covered in the client SDK.

> sentry -> separate socket

This also doesn't need to be exposed via the client SDK as it is an internal detail.

> worker storage -> internal socket

So there are two things, one part are some control functions for the storage worker -- for those there is definitely no need to expose them in the client SDK. The other one is the regular storage API which could be useful to have.

**Comment by pro-wh** [comment]
> The `enclaverpc.Transport` service is actually exposed (see [runtime client API](https://github.com/oasisprotocol/oasis-core/blob/master/go/runtime/client/api/api.go#L44)) via the internal socket so it should be covered in the client SDK.

oh right. I had gotten that right the first time :laughing:

**Comment by pro-wh** [comment]
alright, let's close this. open new issues for the separate sockets if we later desire them
