### ISSUE TITLE
Sapphire.generateSigningKeyPair returns wrong secret key, and Sapphire.generateCurve25519KeyPair returns zeros

### ISSUE THREAD

**Issue by HarryR** [oasisprotocol/oasis-sdk#1310]
Hi

I am testing the functionality in https://github.com/oasisprotocol/oasis-sdk/blob/main/runtime-sdk/modules/evm/src/precompile/confidential.rs and noticed some things are broken or do not work according to the documentation or how you would expect it to work.

Note: I'm using  ghcr.io/oasisprotocol/sapphire-dev:latest-2023-03-16-git35feb7c docker image for testing.

-----------------

The first issue is that `generateCurve25519KeyPair` function always returns zeros as the encoded public point.

```solidity
(a, b) = Sapphire.generateCurve25519KeyPair(abi.encodePacked(block.number));
emit PublicKey(a);
emit PublicKey(b);
```

Example output:

```
Event PublicKey with args 0x0000000000000000000000000000000000000000000000000000000000000000
Event PublicKey with args 0x602bf9ede69ca09921013066fd8fa5a80c976199f774de7c8008ecc55704d05a
```

--------------

The second issue is using `Sapphire.generateSigningKeyPair(SigningAlg.Ed25519Pure, secret)`, it returns an expanded secret key (see: https://docs.rs/ed25519-dalek/latest/src/ed25519_dalek/secret.rs.html#285) but the public point it returns does not match the ExpandedSecretKey, it instead matches the public point of the seed provided.

While this is odd, it does however mean I can perform point multiplication to generate Ed25519 public key from from a secret, which is what I needed so it can be used with `Sapphire.deriveSymmetricKey` between a keypair owned by the contract and a public key provided by a user.

```python
from hashlib import sha512
import kat     # https://raw.githubusercontent.com/pyca/ed25519/main/ed25519.py
import ed25519 # https://github.com/warner/python-ed25519

# Replicate the functionality of Sapphire.generateSigningKeyPair(SigningAlg.Ed25519Pure, secret)
# Example taken from smart contract invocation
# eo = [secret] + generateSigningKeyPair(SigningAlg.Ed25519Pure, secret)
# For example:
eo = '0x8b9dbf9a46503ae803a49e10fbc31d4423dbb77ec8af684e985362adc66a5aa5,0xff948e51e35579b544a248d8a72bc71a8bc68bd967009b7bdb8afd35e2785ea0,0x005fdb76cbe2d94ec262c6f896f609aae0da5f2bd1160a28f61b22e518beb978cd431154b0c79b101b9a6cd2c67ca87caac050ae6a73c1e4bf14435fb2097122'
eo = '0x88d64f6b4d86909cbffcf1a1fdd579e51f4c86e838234e0dfc10d2047b8f8476,0xd4daf1198d87fec2f65ec5ad7d962898bc5e5d02027dc885d5b0c3fdae7aa16a,0xa8021ffedf11065347c0ac2f37a22bdec67fcdd1a69650857692e5c47b735e71ed7300db501db5f29ed72ce091312cd908fbd40a557408462c7fa65cb1e687fb'
raw_example = [bytes.fromhex(_[2:]) for _ in eo.split(',')]
secret,public,esk = raw_example

# Both pure python & C library agree that public == B * secret
assert kat.publickey_unsafe(secret) == public
sk = ed25519.SigningKey(secret)
assert sk.get_verifying_key().to_bytes() == public

# This is essentually useless data when using Ed25519Pure
# The returned public key isn't 
x = list(sha512(secret).digest())
x[0] &= 0xf8;  # Make it a multiple of 8 to avoid small subgroup attacks.
x[31] &= 0x7f; # Clamp to < 2^255 - 19
x[31] |= 0x40  # Clamp to >= 2^254
x = bytes(x)
assert x == esk

# Neither of the values returned by generateSigningKeyPair in 2nd value represent the public key it returned in 1st value
sk2 = ed25519.SigningKey(x[:32])
pk2 = sk2.get_verifying_key()
print(pk2.to_bytes().hex())
sk3 = ed25519.SigningKey(x[32:])
pk3 = sk3.get_verifying_key()
print(pk3.to_bytes().hex())

# Ensure we can construct the output generated by Sapphire EVM
replicated_output = [secret, public, x]
assert raw_example == replicated_output
```

**Comment by HarryR** [comment]
The 'secret' returned from `generateSigningKeyPair` is useful as the first 32 bytes are the derived x25519 secret for use with `Sapphire.deriveSymmetricKey`. But, without a working `CURVE25519_PUBLIC_KEY` operation I needed to convert the Ed25519 point to its montgomery coordinates (see js snippet below).

Using this method I am able to establish a known secret between contract and an ephemeral x25519 key.

```javascript

const nacl = require('tweetnacl');

// XXX: why isn't this exported in nacl.lowlevel, field inversion is useful!
function inv25519(o, i) {
  const {gf, S, M} = nacl.lowlevel;
  var c = gf();
  var a;
  for (a = 0; a < 16; a++) c[a] = i[a];
  for (a = 253; a >= 0; a--) {
    S(c, c);
    if(a !== 2 && a !== 4) M(c, c, i);
  }
  for (a = 0; a < 16; a++) o[a] = c[a];
}

/**
 * convert ed25519 public key to its montgomery coordinate
 * 
 * ed25519 is birationally equiv. to montgomery curve
 * 
 * (u, v) = ((1+y)/(1-y), sqrt(-486664)*u/x)
 * (x, y) = (sqrt(-486664)*u/v, (u-1)/(u+1))
 * 
 * Examples:
 *  - https://github.com/StableLib/stablelib/blob/master/packages/ed25519/ed25519.ts#L861 (convertPublicKeyToX25519)
 *  - https://docs.rs/ed25519_to_curve25519/latest/src/ed25519_to_curve25519/lib.rs.html#1-108
 */
function ed25519_public_to_mont25519(publicKey) {
  const {gf, pack25519, unpack25519, A, Z, M} = nacl.lowlevel;
  var AY = gf();
  unpack25519(AY, publicKey);
  var one_minus_y = gf([1]);
  Z(one_minus_y, one_minus_y, AY);
  inv25519(one_minus_y, one_minus_y);
  var x = gf([1]);
  A(x, x, AY);
  M(x, x, one_minus_y);
  var o = new Uint8Array(32);
  pack25519(o, x);
  return o;
}
```

**Comment by kostko** [comment]
Thanks for your report and interest in confidential contracts! I see that you are using the `sapphire-dev` image [which is currently using Sapphire 0.4.0 (the version also deployed on Mainnet)](https://github.com/oasisprotocol/oasis-web3-gateway/blob/f2b38f138393675fd78c75f90888f817d25ffd2a/docker/sapphire-dev/Dockerfile#L21). The `CURVE25519_PUBLIC_KEY` operation has only been added in 0.5.0-testnet (which is currently deployed on Sapphire Testnet).

Can you test the operation out on Sapphire Testnet ([parameters](https://docs.oasis.io/dapp/sapphire/#testnet), [faucet](https://faucet.testnet.oasis.dev/)) and report back?

**Comment by HarryR** [comment]
Ah.

Modifying the following parameters similar to https://github.com/oasisprotocol/oasis-web3-gateway/pull/375/files so I can run 0.5.0 locally has fixed the problem. Existing tests work and the `CURVE25519_PUBLIC_KEY` builtin works as expected.

```Dockerfile
ENV OASIS_CORE_VERSION=22.2.7
ENV PARATIME_VERSION=0.5.0-testnet
```

**Comment by kostko** [comment]
Thanks for confirming!
