### ISSUE TITLE
Random failures with contracts on sapphire-dev

### ISSUE THREAD

**Issue by HarryR** [oasisprotocol/oasis-sdk#1353]
For a testcase see: https://gist.github.com/HarryR/ec79308a529f6688abc4c4663f9e7fbb - this overwrites and reads back a sliding window of key/value pairs. Sometimes it fails while performing the write, other times when performing the read.

Tested with Sapphire 0.5.1, 0.5.0 (via https://github.com/oasisprotocol/oasis-web3-gateway/pull/375) and 0.4.0 (via sapphire-dev) and they all exhibit the same behavior, specific versions tested:
 * sapphire-dev local (oasis-core: 22.2.6, sapphire-paratime: 0.5.1-testnet, oasis-web3-gateway: 3.3.0)
 * sapphire-dev 2023-04-13-git0f0fd11 (oasis-core: 22.2.6, sapphire-paratime: 0.4.0, oasis-web3-gateway: 3.2.0-git0f0fd11)
 * sapphire-dev local (oasis-core: 22.2.7, sapphire-paratime: 0.5.0-testnet, oasis-web3-gateway: 3.2.0-gitf2b38f1+dirty)

This is causing random failures in several contracts which read & write from several common keys in sequence. Simpler contracts that only run once or twice are fine, but more complex stuff fails randomly and inconsistently after a few calls. Once the failure has occurred no accounts can interact with the contract.. They all error with the same exception.

Have tried changing .txn_scheduler.batch_flush_timeout=10000000000 (10 seconds apparently?) but saw no difference, unsure of which others tunables to change.

I have run the tests on testnet and it does not fail in the same way.

 * Deployed contract: [0x730f21cd99a565accf9ceab4800d33a032afb04aecac6f8bbe2d53b22dca8806](https://testnet.explorer.sapphire.oasis.dev/address/0x2bdCC0de6bE1f7D2ee689a0342D76F52E8EFABa3) using 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 test account and did ~20 successful transactions.

**Comment by CedarMist** [comment]
This seems to have been resolved after switching to mock backend and manually progressing epochs.
