### ISSUE TITLE
EVM: add SEC P256 R1 family to generation, signing & verification

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-sdk#1417]
**This is a work-in-progess ticket.**

The secp256r1 (OID1.2.840.10045.3.1.7) curve is widely used in Web2 applications, everything from WebAuthN and JWT to SSL certificates. This ticket proposes adding support for the curve to the keypair generation, signing & verification precompiles for secp256r1 and EcDSA.

A constant-gas implementation of secp256r1 scalar multiply in Ethereum costs approx 1,500,000 gas[1], given that Web2 authentication is so widely used and can be combined with confidential EVM contracts to enable many interesting use cases, it would good for us to fully support the curve and its most widely used signing algorithm.

[1] https://raw.githubusercontent.com/CedarMist/demo-authzn/main/backend/contracts/SECP256R1.sol

Currently the some things are returned in DER encoded form, this is OK as we have code in sapphire-contracts to decode, it's just annoying as it's a variable length form which requires parsing to do useful things with in Solidity.

TODO:

 - [x] Decide on DER encoding or something more Solidity friendly (e.g. plain ABI encoding of 256bit uints / bytes32 values)
    - DER decoding is annoying in Solidity, it's just as hard to do DER encoding.
    - If values are constant sized, e.g. two uint256 values as a 64 byte long `bytes memory`, it's easy to construct this, and much less annoying than DER coding
    - ABI encoded, is easiest to work with from Solidity
    - It's cheaper to pass (X,Y) or (r,s) as 64 bytes and transform to/from DER in client side code.
 - [x] Decide on public key format returned by Generate, then accepted by Verify
    -   needs to be consistent but also easy to work with from Solidity
 - [ ] Generate test vectors of secp256r1+EcDSA signatures & keypairs, anomalous values etc.
 - [ ] Decide on gas price, I assume it would be comparable to current secp256k1 implementations
 - [x] Find Rust library implementing secp256r1 with EcDSA
   - Must have direct access to scalar multiply rather than being hidden in wrapper, as this will be necessary for another precompile proposal.

-----

New SigningAlg enum:

 * Secp256r1PrehashedSha256 = 7

And support for secp256r1+EcDSA for the following precompiles:

 * 0x0100000000000000000000000000000000000006 (Sign Digest)
 * 0x0100000000000000000000000000000000000007 (Verify Digest)

-----

The generate operation will work as follows:

 * Input
    * Require 32 byte `seed`
    * Require `alg==7`
 * Validates `seed` is big-endian uint256
    * in range of `[1, N-1]` where `N` is the group order
 * Returns 33 bytes
    * Compressed curve point for public key as per https://www.secg.org/sec1-v2.pdf  2.3.3 pg 10
      * 1 byte `0x02` or `0x03` prefix
      * 32 byte X coordinate

-----

The Signing operation will work as follows:

 * Input
   * Require 32 byte `secretKey`
   * Require 32 byte `contextOrHash`
   * Require 0 byte `message`
 * Internal secret `k` scalar derived deterministically by hashing `secretKey` and `contextOrHash`
 * Returns the `r` and `s` parameters of the signature
    * DER encoded Sequence of two Integers, `r` then `s` as returned from `to_der`

-----

The Verification operation will work as follows:

 * Input
   * Require 33 byte `publicKey`
     * Compressed public key, `0x02` or `0x03` prefix followed by 32 bytes X coordinate
   * Require 32 byte `contextOrHash`
   * Require 0 byte `message`
   * Require `signature` (format TBD)
 * Use EcDSA to check signature
 * Returns ABI encoded bool
   * `true` if valid, or `false` if invalid or validation fails.

------------

Follow-on tasks:

 - [ ] Update `Sapphire.sol` in sapphire-paratime/contracts to add new SigningAlg
 - [ ] Update documentation with details of new signing, verification & key generation options.

**Comment by kostko** [comment]
> Find Rust library implementing secp256r1 with EcDSA

Given that we are using k256 for secp256k1, we should probably use [p256](https://crates.io/crates/p256) for secp256r1.
