### ISSUE TITLE
Add support for consensus pool:common and pool:fee-accumulator

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-sdk#1508]
Currently, only the runtime's common pool and fee accumulator is resolved in https://github.com/oasisprotocol/oasis-sdk/blob/main/client-sdk/go/helpers/address.go. Add support for consensus common pool and fee-accumulator as well by passing the ParaTime instance to ResolveAddress(). If the instance is defined, then use the ParaTime's address, otherwise return the consensus address.

Perhaps it would make sense to migrate most of the helpers/address.go to Oasis CLI and get rid of all the pools, separators and other CLI-related literals?

**Comment by kostko** [comment]
Yes, I agree that this should be moved to the CLI.
