### ISSUE TITLE
sr25519 precompile for EVM sdk

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-sdk#1968]
Re: #304

In [evm/src/precompile/confidential.rs](https://github.com/oasisprotocol/oasis-sdk/blob/main/runtime-sdk/modules/evm/src/precompile/confidential.rs) we support Ed25519, Secp256k1, Secp256r1 and Secp384r1.

Sr25519 is also supported in [crypto/signature/mod.rs](https://github.com/oasisprotocol/oasis-sdk/blob/main/runtime-sdk/src/crypto/signature/mod.rs)

For Polkadot compatibility, we should support sr25519 signing & verification, as all the necessary support is there.

However, it seems substrate key derivation is not compatible with our ADR-8. To make sure it's compatible with Polkadot it will be necessary to take test vectors from Polkadot ecosystem to be sure signatures, keygen & verification works correctly.

**Comment by kostko** [comment]
> However, it seems substrate key derivation is not compatible with our ADR-8. To make sure it's compatible with Polkadot it will be necessary to take test vectors from Polkadot ecosystem to be sure signatures, keygen & verification works correctly.

I don't think this is relevant here as the precompiles allow raw signatures and don't do any derivation?

**Comment by kostko** [comment]
Also note that currently there is no `MemorySigner` implementation for sr25519, so only verification is implemented. It should be easy to add one though and update the relevant parts. For EVM support, the main thing is calibrating the gas costs. Should probably be similar to ed25519?

**Comment by CedarMist** [comment]
https://github.com/paulmillr/micro-sr25519 is a minimal implementatoin of the sr25519 cryptography for Polkadot.

I will make some test cases for this
