### ISSUE TITLE
chrome extension wallet  - import account

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-sdk#270]
I tried to import the testing account [alice](https://github.com/oasisprotocol/oasis-sdk/blob/9bc4d2d183710dd3476f10327cd21518976d9248/client-sdk/go/testing/testing.go#L39) into the chrome ext by the following steps:

* On the account management page of the chrome ext, click "Import"
* Click "Private Key"
* Key in "alice" as the account name
* Paste alice's private key. I tried base64 private key "OPYg5hO22BvHgHmtjo/dZgyn/+efqDhcAfcZ6NsMKhc=" and hex private key "38f620e613b6d81bc78079ad8e8fdd660ca7ffe79fa8385c01f719e8db0c2a17". But both failed

Any advice?

**Comment by ptrus** [comment]
> I tried base64 private key "OPYg5hO22BvHgHmtjo/dZgyn/+efqDhcAfcZ6NsMKhc=" 

How did you get that private key? It looks like that's not the full private key, this is the private key of the "alice" test account. This is the full private-key:
`OPYg5hO22BvHgHmtjo/dZgyn/+efqDhcAfcZ6NsMKhc1w/M1bdhTZP66A1S1Ra2hCdG9s4v11hJoF9uMcs/WkQ==`

and i am able to import this key into the chrome extension wallet.

**Comment by livelybug** [comment]
> How did you get that private key?

```go
	pk := sha512.Sum512_256([]byte("oasis-runtime-sdk/test-keys: alice"))
	sEnc := base64.StdEncoding.EncodeToString(pk[:])
	fmt.Println(sEnc)  // OPYg5hO22BvHgHmtjo/dZgyn/+efqDhcAfcZ6NsMKhc=
```
Is it correct?

Something after the issue is reported.:
The chrome ext wallet developer, niuniu-Bit Cat(oasisscan.com), gave me an updated chrome ext wallet after seeing the issue.
Then I was able to import the private key "OPYg5hO22BvHgHmtjo/dZgyn/+efqDhcAfcZ6NsMKhc=", and the address displayed correctly too.
But I cannot verify if the account was correctly imported as the balance couldn't be verified on the chrome ext, which is another issue.

**Comment by ptrus** [comment]
`sha512.Sum512_256([]byte("oasis-runtime-sdk/test-keys: alice"))` is actually just the seed. This is how the full key is derived from the seed:
https://github.com/oasisprotocol/curve25519-voi/blob/b12728c4e0d8487c89cbe8765a3e3426a699543b/primitives/ed25519/ed25519.go#L554-L577

I guess Bit Cat added support for deriving the PK from the seed to the extension for you.

---

> But I cannot verify if the account was correctly imported as the balance couldn't be verified on the chrome ext, which is another issue.

Hm

**Comment by livelybug** [comment]
oops, I mixed up the ed25519 and [secp256k1 signer](https://github.com/oasisprotocol/oasis-sdk/blob/4daa02dd2655f459ec918def7ed1adb1ca640177/client-sdk/go/testing/testing.go#L28).
