### ISSUE TITLE
is the local testnet slower now?

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-sdk#308]
I've started to see e2e-ts-web-rt time out (2 minute timeout after node socket is created). simple-keyvalue fails, then simple-consensus passes. would simple-keyvalue pass with more time?

**Comment by kostko** [comment]
Why would it be slower? Can we get any node logs?

**Comment by pro-wh** [comment]
huh, seems like it's not that. a recent pass has this
```
  playground
    ✓ finishes simple-keyvalue (53668ms)
    ✓ finishes simple-consensus (4743ms)
```
53 seconds, well under the timeout. must be something else.
