### ISSUE TITLE
Native cryptography function imports

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-sdk#368]
The smart contracts module should provide a set of native cryptography function imports (probably under the `crypto` WASM module) in order to avoid the cost of implementing them in WASM.

Currently this should include the signature schemes used in the SDK:
* Ed25519 (verify, batch verify)
* Sr25519 (verify, batch verify)
* Secp256k1 (verify, recover pubkey)

Appropriate gas costs and upper limits (message size, batch size) should be added for each of these operations.

**Comment by Yawning** [comment]
Beyond the implementation cost, there are no guarantees on the timing characteristics of any WASM instructions, rendering constant-time cryptography implementations currently impossible (or at least very difficult).

While none of the operations you listed that you want to provide use secret data, effort must be made to discourage implementing any cryptography in WASM at all.
