### ISSUE TITLE
Use HashedStore for EVM contract storage

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-sdk#376]
EVM contract storage should use `HashedStore` introduced in #263 (should be trivial to plug in after that is merged).

**Comment by anonymousGiga** [comment]
How to use hashedstore to store contracts? Would you describe it more specifically?  @kostko

**Comment by kostko** [comment]
> How to use hashedstore to store contracts? Would you describe it more specifically?

Yeah, there is now a [HashedStore](https://api.docs.oasis.dev/oasis-sdk/oasis_runtime_sdk/storage/struct.HashedStore.html) that can be used similarly as what we do in the [contracts module](https://github.com/oasisprotocol/oasis-sdk/blob/main/runtime-sdk/modules/contracts/src/store.rs). So this should be used for storing any keys that can be set from within the EVM as my understanding is that the EVM implementation does not hash keys by itself?
