### ISSUE TITLE
Consider replacing `StoreKey` with `AsRef<[u8]>`

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/oasis-sdk#76]
`AsRef<[u8]>` seems about what the `StoreKey` trait is going for. It also comes with a shiny new const generic impl. Whether this issue is relevant depends on whether `StoreKey` will ever not be just `as_store_key()`.

**Comment by kostko** [comment]
Yeah StoreKey just makes it more explicit, but maybe you would always want the same result as `as_ref`. In this case we could just simplify and use `AsRef` directly.
