### ISSUE TITLE
cli: Add support for referencing wallets in addresses

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-sdk#891]
Similar to how you can use special address references like `paratime:foo`, `pool:rewards` etc. it would be great if one could use `wallet:name` to reference a local wallet's address.

**Comment by matevz** [comment]
`wallet:name` should now probably be called `account:name` for consistency.
Also `test:{alice|bob|charlie|dave}` should be added for hardcoded testing accounts.
