### ISSUE TITLE
EVM: eth_estimateGas does not fail when reverted

### ISSUE THREAD

**Issue by chitter99** [oasisprotocol/oasis-sdk#965]
Noticed that Emerald is not failing eth_estimateGas requests for tx that are reverting. 

Uniswap (and forks like yuzu on Emerald) relays on gas estimate failing when the tx is reverted. As an example to find out if an ERC20 takes a fee on transfer.

Created a repo to show this behaviour. https://github.com/chitter99/emerald-call-revert

**Comment by kostko** [comment]
The gas estimation not failing on (simulated) transaction errors is the expected behavior of the `core.EstimateGas` query method:
https://github.com/oasisprotocol/oasis-sdk/blob/8f6a035bc29213f161fc00b94ee9a9bab3d7b759/runtime-sdk/src/modules/core/mod.rs#L407-L414

One way to not change the default while addressing the above would be to add an optional argument by which the caller (e.g. in case Web3/Emerald this would be the Emerald Web3 Gateway) could specify to propagate errors instead.

**Comment by chitter99** [comment]
Thx for the quick reply! That would solve this issue. Yuzu could add this to their gateway.

**Comment by ptrus** [comment]
This has been fixed in the oasis-sdk and will be in affect with the  next emerald paratime upgrade

**Comment by chitter99** [comment]
> This has been fixed in the oasis-sdk and will be in affect with the next emerald paratime upgrade

Thank you for the quick resolution. Can you help me get this parameter working with a JSON-RPC provider?
Using ethers js I'm trying to send a request via:
```
const tx = await test.populateTransaction.callShouldRevert();
const block = ethers.utils.hexValue(ethers.provider.blockNumber);
const est = await ethers.provider.send("eth_estimateGas", [tx, block]);
```
I expected to be able to add another parameter which represents the propagate_failures arg. Hence: 
```
const est = await ethers.provider.send("eth_estimateGas", [tx, block, true]);
```
But this fails with `ProviderError: too many arguments, want at most 2`.

How can we use this without using the `ts-web` library directly?

**Comment by kostko** [comment]
Once this becomes part of a release it will be enabled automatically without you needing to add any arguments (e.g. it should just work).

The following things need to happen first though:

- New Emerald Testnet release that includes the updated SDK.
- Updated Emerald Web3 Gateway that enables this option by default for web3 estimate gas calls.
- Emerald Testnet upgrade deployment.

After sufficient testing this can move to Mainnet as well. The release/testing process is underway.

**Comment by chitter99** [comment]
Thanks! Tested it and works as expected!

**Comment by ptrus** [comment]
Great! It will be included on the mainnet in the next Emerald mainnet update (not yet scheduled, but likely next week).
